In [24]:
import pandas as pd

df = pd.read_csv('dataset\podes2024_pendidikan.csv')

df.head()

<>:3: SyntaxWarning: invalid escape sequence '\p'
<>:3: SyntaxWarning: invalid escape sequence '\p'
C:\Users\VICTUS\AppData\Local\Temp\ipykernel_28652\258848232.py:3: SyntaxWarning: invalid escape sequence '\p'
  df = pd.read_csv('dataset\podes2024_pendidikan.csv')

,IDDESA,R101,R102,R103,R104,NAMA_PROV,NAMA_KAB,NAMA_KEC,NAMA_DESA,R305A,...,R711JK4,R1001A,R1001B1,R1001B2,R1001C1,R1001C2,R1001C3,R1005A,R1005B,R1005C
0,1101010001,11,1,10,1,ACEH,SIMEULUE,TEUPAH SELATAN,LATIUNG,3,...,0,1,2,1,3,0,0,0,1,2
1,1101010002,11,1,10,2,ACEH,SIMEULUE,TEUPAH SELATAN,LABUHAN BAJAU,3,...,0,1,1,1,3,0,0,0,1,2
2,1101010003,11,1,10,3,ACEH,SIMEULUE,TEUPAH SELATAN,SUAK LAMATAN,3,...,0,1,1,1,3,0,0,0,1,2
3,1101010004,11,1,10,4,ACEH,SIMEULUE,TEUPAH SELATAN,ANA AO,3,...,0,1,1,1,3,0,0,0,1,3
4,1101010005,11,1,10,5,ACEH,SIMEULUE,TEUPAH SELATAN,LATALING,3,...,0,1,1,1,3,0,0,0,0,4

In [25]:
import pandas as pd

# Baca layout
layout = pd.read_excel("podes_fokus_padat.xlsx")

# Mapping kode → label
rename_dict = dict(zip(layout["Name"].str.lower(), layout["Label_Short"]))

# Samain case kolom dataset
df.columns = df.columns.str.lower()

# Rename kolom pakai layout
df = df.rename(columns=rename_dict)

# Bersihin nama kolom: 
#  - lowercase
#  - ganti spasi dengan underscore
#  - hapus karakter non-alfanumerik
df.columns = (
    df.columns.str.lower()
              .str.replace(" ", "_")
              .str.replace(r"[^\w]", "", regex=True)  # buang karakter aneh
)

# Simpan hasil
df.to_csv("dataset_r7_clean.csv", index=False)

print("Kolom sudah diganti nama deskriptif tanpa spasi.")

Kolom sudah diganti nama deskriptif tanpa spasi.

In [1]:
import pandas as pd
df = pd.read_csv("dataset_r7_clean.csv")
df.head()

FileNotFoundError: [Errno 2] No such file or directory: 'dataset_r7_clean.csv'

In [5]:
import pandas as pd

df = pd.read_csv("dataset/dataset.csv")
df.head()

,iddesa,nama_prov,nama_kab,nama_kec,nama_desa,topografi_wilayah_desakelurahan,keluarga_pengguna_listrik_pln,keluarga_pengguna_listrik_non_pln,keluarga_non_listrik,paud_negeri,...,surat_miskinsktm_dikeluarkan_desakelurahan_2023_surat,lalu_lintas_desa,jenis_permukaan_jalan,penggunaan_jalan_darat,keberadaan_angkutan_umum,operasional_angkutan_umum_utama,jam_operasi_angkutan_umum,jumlah_menara_bts,jumlah_layanan_operator,kekuatan_sinyal
0,1101010001,ACEH,SIMEULUE,TEUPAH SELATAN,LATIUNG,Dataran,85,0,0,0,...,20,Darat,Diperkeras,SepanjangTahun,TidakAda,TidakBerlaku,TidakBerlaku,0,1,Kuat
1,1101010002,ACEH,SIMEULUE,TEUPAH SELATAN,LABUHAN BAJAU,Dataran,159,0,0,0,...,25,Darat,AspalBeton,SepanjangTahun,TidakAda,TidakBerlaku,TidakBerlaku,0,1,Kuat
2,1101010003,ACEH,SIMEULUE,TEUPAH SELATAN,SUAK LAMATAN,Dataran,155,0,0,0,...,45,Darat,AspalBeton,SepanjangTahun,TidakAda,TidakBerlaku,TidakBerlaku,0,1,Kuat
3,1101010004,ACEH,SIMEULUE,TEUPAH SELATAN,ANA AO,Dataran,172,0,4,0,...,275,Darat,AspalBeton,SepanjangTahun,TidakAda,TidakBerlaku,TidakBerlaku,0,1,Lemah
4,1101010005,ACEH,SIMEULUE,TEUPAH SELATAN,LATALING,Dataran,137,0,0,0,...,115,Darat,AspalBeton,SepanjangTahun,TidakAda,TidakBerlaku,TidakBerlaku,0,0,TidakAda

In [ ]:
import pandas as pd
df = pd.read_csv("dataset/dataset.csv")

map_kemudahan = {0: "TidakBerlaku", 1: "SangatMudah", 2: "Mudah", 3: "Sulit", 4: "SangatSulit"}


# Cari semua kolom yang ada kata 'kemudahan' di nama kolomnya
kemudahan_cols = [col for col in df.columns if "kemudahan_mencapai" in col.lower()]

# Apply mapping ke semua kolom tsb
df[kemudahan_cols] = df[kemudahan_cols].apply(lambda col: col.map(map_kemudahan))

df.to_csv("dataset_r7_clean.csv", index=False)
print(f"{len(kemudahan_cols)} kolom 'kemudahan' berhasil di-decode ✅")

24 kolom 'kemudahan' berhasil di-decode ✅

In [28]:
map_topografi = {1: "Tebing", 2: "Lereng", 3: "Dataran", 4:"Lembah"}

topografi_col = [col for col in df.columns if col.startswith("topografi_")]

df[topografi_col] = df[topografi_col].apply(lambda col: col.map(map_topografi))

df.to_csv("dataset_r7_clean.csv", index=False)
print(f"{len(topografi_col)} kolom 'topografi' berhasil di-decode ✅")

1 kolom 'topografi' berhasil di-decode ✅

In [29]:
map_permukiman_tebing = {0: 'TidakBerlaku', 1: 'Ada', 2: 'TidakAda'}

col = [c for c in df.columns if "penduduk_puncaktebinglereng" in c.lower()][0]

df[col] = df[col].map(map_permukiman_tebing)
df.to_csv("dataset_r7_clean.csv", index=False)
print(f"Kolom '{col}' berhasil di-decode ✅")

Kolom 'keberadaan_permukiman_penduduk_puncaktebinglereng' berhasil di-decode ✅

In [30]:
map_wilayah_hutan = {1: "DidalamHutan", 2: "SekitarHutan", 3: "LuarHutan"}

col = [c for c in df.columns if "lokasi_wilayah" in c.lower()][0]
df[col] = df[col].map(map_wilayah_hutan)
df.to_csv("dataset_r7_clean.csv", index=False)
print("data berhasil di decode")

data berhasil di decode

In [31]:
map_permukiman_tebing = {0: 'TidakBerlaku', 1: 'HutanNegara', 2: 'HutanHak', 3:'HutanAdat'}

col = [c for c in df.columns if "status_kawasan_hutanhutan" in c.lower()][0]

df[col] = df[col].map(map_permukiman_tebing)
df.to_csv("dataset_r7_clean.csv", index=False)
print(f"Kolom '{col}' berhasil di-decode ✅")

Kolom 'status_kawasan_hutanhutan' berhasil di-decode ✅

In [32]:
map_ketergantung = {0: 'TidakBerlaku', 1: 'Tinggi', 2: 'Sedang', 3:'Rendah', 4: 'TidakTergantung'}

col = [c for c in df.columns if "ketergantungan_penduduk" in c.lower()][0]
df[col] = df[col].map(map_ketergantung)
df.to_csv("dataset_r7_clean.csv", index=False)
print(f"Kolom '{col}' berhasil di-decode ✅")

Kolom 'ketergantungan_penduduk_kawasan_hutanhutan' berhasil di-decode ✅

In [33]:
map_klb = {1: 'Ada', 2: 'TidakAda'}

# Cari semua kolom yang ada kata 'klb'
klb_cols = [c for c in df.columns if "klb" in c.lower()]

# Apply mapping ke semua kolom tsb
df[klb_cols] = df[klb_cols].apply(lambda col: col.map(map_klb))
df.to_csv("dataset_r7_clean.csv", index=False)

print(f"{len(klb_cols)} kolom berhasil di-decode ✅")

map_pangan = {1: 'Ada', 2: 'TidakAda'}

col = [c for c in df.columns if "kejadian_kerawanan_pangan" in c.lower()][0]
df[col] = df[col].map(map_pangan)
df.to_csv("dataset_r7_clean.csv", index=False)
print(f"Kolom '{col}' berhasil di-decode ✅")

9 kolom berhasil di-decode ✅
Kolom 'kejadian_kerawanan_pangan' berhasil di-decode ✅

In [ ]:
map_lalulintas = {1: "Darat", 2: "Air", 3: "DaratdanAir", 4: "Udara"}

col = [c for c in df.columns if "lalu_lintas" in c.lower()][0]
print(col)
df[col] = df[col].map(map_lalulintas)
df.to_csv("dataset_r7_clean.csv", index=False)
print(f"Kolom '{col}' berhasil di-decode ✅")

lalu_lintas_desakelurahan_melalui
Kolom 'lalu_lintas_desakelurahan_melalui' berhasil di-decode ✅

In [35]:
map_jenis_permukaan = {0: "TidakBerlaku", 1: "AspalBeton", 2: "Diperkeras", 3: "Tanah", 4: "Lainnya"}

col = [c for c in df.columns if "jalan_terluas" in c.lower()][0]
df[col] = df[col].map(map_jenis_permukaan)
df.to_csv("dataset_r7_clean.csv", index=False)
print(f"Kolom '{col}' berhasil di-decode ✅")

Kolom 'jenis_permukaan_jalan_terluas' berhasil di-decode ✅

In [36]:
map_jalan_darat = {0: 'TidakBerlaku', 1: 'SepanjangTahun', 2: 'SepanjangTahunKecualiTertentu', 3: 'MusimKemarau', 4: 'TidakDapatDilalui'}

col = [c for c in df.columns if "jalan_darat" in c.lower()][0]
df[col] = df[col].map(map_jalan_darat)
df.to_csv("dataset_r7_clean.csv", index=False)
print(f"Kolom '{col}' berhasil di-decode ✅")

Kolom 'jalan_darat_dilalui_kendaraan_bermotor_roda_4_lebih' berhasil di-decode ✅

In [37]:
map_angkot = {1: 'AdaTrayekTetap', 2: 'AdaNonTrayekTetap', 3: 'TidakAda'}

col = [c for c in df.columns if "keberadaan_angkutan_umum" in c.lower()][0]
df[col] = df[col].map(map_angkot)
df.to_csv("dataset_r7_clean.csv", index=False)
print(f"Kolom '{col}' berhasil di-decode ✅")

Kolom 'keberadaan_angkutan_umum' berhasil di-decode ✅

In [38]:
map_operasional = {0:'TidakBerlaku', 1: 'SetiapHari', 2: 'Tertentu'}

col = [c for c in df.columns if "operasional_angkutan_umum_utama" in c.lower()][0]
df[col] = df[col].map(map_operasional)
df.to_csv("dataset_r7_clean.csv", index=False)
print(f"Kolom '{col}' berhasil di-decode ✅")

Kolom 'operasional_angkutan_umum_utama' berhasil di-decode ✅

In [40]:
map_jam_operasional = {0:'TidakBerlaku', 1: 'SetiapWaktu', 2: 'SiangAtauMalam'}

col = [c for c in df.columns if "jam_operasi_angkutan_umum_utama" in c.lower()][0]
df[col] = df[col].map(map_jam_operasional)
df.to_csv("dataset_r7_clean.csv", index=False)
print(f"Kolom '{col}' berhasil di-decode ✅")

Kolom 'jam_operasi_angkutan_umum_utama' berhasil di-decode ✅

In [41]:
map_sinyal = {1: 'SangatKuat', 2: 'Kuat', 3: 'Lemah', 4: 'TidakAda'}

col = [c for c in df.columns if "kekuatan_sinyal" in c.lower()][0]
df[col] = df[col].map(map_sinyal)
df.to_csv("dataset_r7_clean.csv", index=False)
print(f"Kolom '{col}' berhasil di-decode ✅")

Kolom 'kekuatan_sinyal' berhasil di-decode ✅

In [1]:
import pandas as pd
import pyarrow as pa
import pyarrow.parquet as pq

df = pd.read_csv("dataset/dataset.csv")
table = pa.Table.from_pandas(df)
pq.write_table(table, "dataset/dataset.parquet")

In [3]:
df = pd.read_parquet("dataset/dataset.parquet")
df.head()

,iddesa,nama_prov,nama_kab,nama_kec,nama_desa,topografi_wilayah_desakelurahan,keluarga_pengguna_listrik_pln,keluarga_pengguna_listrik_non_pln,keluarga_non_listrik,paud_negeri,...,surat_miskinsktm_dikeluarkan_desakelurahan_2023_surat,lalu_lintas_desa,jenis_permukaan_jalan,penggunaan_jalan_darat,keberadaan_angkutan_umum,operasional_angkutan_umum_utama,jam_operasi_angkutan_umum,jumlah_menara_bts,jumlah_layanan_operator,kekuatan_sinyal
0,1101010001,ACEH,SIMEULUE,TEUPAH SELATAN,LATIUNG,Dataran,85,0,0,0,...,20,Darat,Diperkeras,SepanjangTahun,TidakAda,TidakBerlaku,TidakBerlaku,0,1,Kuat
1,1101010002,ACEH,SIMEULUE,TEUPAH SELATAN,LABUHAN BAJAU,Dataran,159,0,0,0,...,25,Darat,AspalBeton,SepanjangTahun,TidakAda,TidakBerlaku,TidakBerlaku,0,1,Kuat
2,1101010003,ACEH,SIMEULUE,TEUPAH SELATAN,SUAK LAMATAN,Dataran,155,0,0,0,...,45,Darat,AspalBeton,SepanjangTahun,TidakAda,TidakBerlaku,TidakBerlaku,0,1,Kuat
3,1101010004,ACEH,SIMEULUE,TEUPAH SELATAN,ANA AO,Dataran,172,0,4,0,...,275,Darat,AspalBeton,SepanjangTahun,TidakAda,TidakBerlaku,TidakBerlaku,0,1,Lemah
4,1101010005,ACEH,SIMEULUE,TEUPAH SELATAN,LATALING,Dataran,137,0,0,0,...,115,Darat,AspalBeton,SepanjangTahun,TidakAda,TidakBerlaku,TidakBerlaku,0,0,TidakAda

In [6]:
import pandas as pd

# contoh data
data = pd.read_csv("dataset/dataset_r7_clean.csv", usecols=[col for col in data.columns if "kemudahan_mencapai" in col.lower()])

# mapping manual sesuai tingkatan
mapping = {
    "TidakBerlaku": 0,
    "SangatMudah": 1,
    "Mudah": 2,
    "Sulit": 3,
    "SangatSulit": 4
}

# apply mapping
data["kemudahan_encoded"] = data["kemudahan_akses"].map(mapping)

print(data)

       iddesa nama_prov  nama_kab        nama_kec      nama_desa  \
0  1101010001      ACEH  SIMEULUE  TEUPAH SELATAN        LATIUNG
1  1101010002      ACEH  SIMEULUE  TEUPAH SELATAN  LABUHAN BAJAU
2  1101010003      ACEH  SIMEULUE  TEUPAH SELATAN   SUAK LAMATAN
3  1101010004      ACEH  SIMEULUE  TEUPAH SELATAN         ANA AO
4  1101010005      ACEH  SIMEULUE  TEUPAH SELATAN       LATALING

  topografi_wilayah_desakelurahan  keluarga_pengguna_listrik_pln  \
0                         Dataran                             85
1                         Dataran                            159
2                         Dataran                            155
3                         Dataran                            172
4                         Dataran                            137

   keluarga_pengguna_listrik_non_pln  keluarga_non_listrik  paud_negeri  ...  \
0                                  0                     0            0  ...
1                                  0                     0            0  ...
2                                  0                     0            0  ...
3                                  0                     4            0  ...
4                                  0                     0            0  ...

   surat_miskinsktm_dikeluarkan_desakelurahan_2023_surat  lalu_lintas_desa  \
0                                                 20                 Darat
1                                                 25                 Darat
2                                                 45                 Darat
3                                                275                 Darat
4                                                115                 Darat

   jenis_permukaan_jalan  penggunaan_jalan_darat  keberadaan_angkutan_umum  \
0             Diperkeras          SepanjangTahun                  TidakAda
1             AspalBeton          SepanjangTahun                  TidakAda
2             AspalBeton          SepanjangTahun                  TidakAda
3             AspalBeton          SepanjangTahun                  TidakAda
4             AspalBeton          SepanjangTahun                  TidakAda

   operasional_angkutan_umum_utama  jam_operasi_angkutan_umum  \
0                     TidakBerlaku               TidakBerlaku
1                     TidakBerlaku               TidakBerlaku
2                     TidakBerlaku               TidakBerlaku
3                     TidakBerlaku               TidakBerlaku
4                     TidakBerlaku               TidakBerlaku

   jumlah_menara_bts  jumlah_layanan_operator  kekuatan_sinyal
0                  0                        1             Kuat
1                  0                        1             Kuat
2                  0                        1             Kuat
3                  0                        1            Lemah
4                  0                        0         TidakAda

[5 rows x 120 columns]